### ISSUE TITLE
Multiple proxy pass trouble

### ISSUE THREAD

**Issue by cazorla19** [knyar/nginx-lua-prometheus#10]
Hello. I tried to monitor Nginx by this library with default configuration. AFAIK, each metric is labeled by HTTP "Host" header by the library. So, I tried to append different proxy locations different host headers.

Here is my config sample:

```
    location ~ ^/api/v1/service1/ {
        proxy_pass http://example.com:9001;
        proxy_set_header Host service1.example.com;
    }

    location ~ ^/api/v1/service2/ {
        proxy_pass http://example.com:9002;
        proxy_set_header Host service2.example.com;
    }

    location ~ ^/api/v1/service3/ {
        proxy_pass http://example.com:9003;
        proxy_set_header Host service3.example.com;
    }

    location ~ ^/api/v1/service4/ {
        proxy_pass http://example.com:9004;
        proxy_set_header Host service4.example.com;
    }
```

The problem is when I scrape metrics from nginx, I receive the metric with only one of them - `service1.example.com`. Also default Nginx hostname, localhost, but no one proxy location more.

So, should it work this way? Is it possible to label metrics by server locations another way? 

Probably, that's my misunderstanding about how does this monitoring work, but I'd be happy to have your advice about this issue.

**Comment by knyar** [comment]
Configuration suggested in `README.md` uses `ngx.var.host`, which is the `Host` header of incoming HTTP request. Your configuration snippet overrides the `Host` header which nginx uses to talk to the backend service defined via `proxy_pass`.

In your case I would suggest adding another metric field that would indicate the service. Something like this:

In `init_by_lua`:
```
metric_requests = prometheus:counter(
  "nginx_http_requests_total", "Number of HTTP requests", {"host", "service", "status"})
```

In your `server` definition:
```
set $proxied_service "default";
location ~ ^/api/v1/service1/ {
  proxy_pass http://example.com:9001;
  set $proxied_service "service1";
}
location ~ ^/api/v1/service2/ {
  proxy_pass http://example.com:9001;
  set $proxied_service "service2";
}
```
In `log_by_lua`:
```
local host = ngx.var.host:gsub("^www.", "")
metric_requests:inc(1, {host, ngx.var.proxied_service, ngx.var.status})
```
