### ISSUE TITLE
How to add the same tags for all metrics?

### ISSUE THREAD

**Issue by qiujiayu** [knyar/nginx-lua-prometheus#101]
How to add the same tags for all metrics?

**Comment by knyar** [comment]
What do you mean by tags?

**Comment by qiujiayu** [comment]
Such as: application name.

**Comment by knyar** [comment]
I assume by "tags" you mean Prometheus labels.

For label names you can define a separate lua table with a list of labels and use it while declaring metrics via `prometheus:counter()`, `prometheus:histogram()` etc.

Similarly, before incrementing counters and recording histogram values, you can create a single lua table with a list of label values and use it in all `inc()` and `observe()` calls.

I hope this helps.
