### ISSUE TITLE
Doesn't work on openresty 1.17.8.1

### ISSUE THREAD

**Issue by mohsenmottaghi** [knyar/nginx-lua-prometheus#103]
We got this error when we try to upgrade from openresty 1.15.8.3 to 1.17.8.1

`
2020/07/12 07:39:43 [error] 1#1: lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: /opt/prometheus.lua:51: loop or previous error loading module 'prometheus_resty_counter')
`

**Comment by irLinja** [comment]
Same here.
Would you please take a look and comment?
@knyar

**Comment by knyar** [comment]
Thanks for reporting this!

I am not using OpenResty myself, and the error message provided does not point to an obvious problem.

If any of the OpenResty users would like to propose a PR improving compatibility, I'd be happy to review it. Ideally we should also add an intergration test for OpenResty similar to the one we have for nginx+libnginx-mod-http-lua.

**Comment by FunkyYang** [comment]
you can put the lua file which in nginx-lua-prometheus add lualib in openresty .and everything wil be ok

**Comment by knyar** [comment]
I am still not sure I understand the issue here.

@FunkyYang, have you been able to identify what changes are necessary for someone who uses this library and needs to upgrade Openresty?

Would anyone like to propose a pull request that documents or fixes this issue, or should I close this?

**Comment by elblivion** [comment]
This looks like a `lua_package_path` issue: https://github.com/openresty/docker-openresty/issues/148

We have been using this project with Openresty over several versions without such issues, installing nginx-lua-prometheus [via OPM](https://opm.openresty.org/package/knyar/nginx-lua-prometheus/). Our lua_package_path has the OPM `/usr/local/openresty/site` path, our applications's path, and the `;;` that adds the standard paths.

```
lua_package_path "/usr/local/openresty/site/?.lua;/app/?.lua;;";
```

**Comment by knyar** [comment]
It does not seem like this is something we can fix, so closing this.
