### ISSUE TITLE
feature request: expose request url endpoint with metric latency 

### ISSUE THREAD

**Issue by frodood** [knyar/nginx-lua-prometheus#108]
hello Knyar,

currently latency logged with only "host", is it possible to get the metric with "host" and "endpoint", for example, request is coming to example.com/checkout/buy.php, I would like to know what the latency for the endpoint, 
`nginx_http_request_duration_seconds_bucket{host="example.com", endpoint="/checkout/buy.php",le="00.010"} 42
 `

**Comment by knyar** [comment]
This is currently possible with this library. The examples in `README.md` are just that -- examples. In your specific environment you would most likely need to define your own set of metrics and metric labels.

Note that adding HTTP path as a metric label is a very easy way to increase metric cardinality (see [this discussion](https://github.com/prometheus/client_golang/issues/491)). If you naively use `ngx.var.uri` as a label value, a simple http scan will suddenly create lots of new metrics which will increase load on your nginx and prometheus server. So in practice you would normally want to derive a limited set of values from HTTP path.
