### ISSUE TITLE
Can histogram support reset method?

### ISSUE THREAD

**Issue by yangxikun** [knyar/nginx-lua-prometheus#112]

**Comment by knyar** [comment]
Yeah, a histogram is just a set of counter metrics, and I think `reset` can be expanded to work for histograms as well (with the usual caveat that it might result in inconsistent data if the metric being reset is actually getting used by other nginx workers).

It's not something I have interest in implementing myself, but I'll be happy to review a PR.

**Comment by yangxikun** [comment]
@knyar Please review https://github.com/knyar/nginx-lua-prometheus/pull/114
