### ISSUE TITLE
openresty1.19.3.1 attempt to index global 'metric_requests' (a nil value)

### ISSUE THREAD

**Issue by fsckzy** [knyar/nginx-lua-prometheus#115]
> CentOS 7
>
> openresty/1.19.3.1

```shell
[root@iZ886g3xpo0Z sbin]# ./nginx -V
nginx version: openresty/1.19.3.1
built by gcc 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC) 
built with OpenSSL 1.1.1h  22 Sep 2020 (running with OpenSSL 1.1.1i  8 Dec 2020)
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --with-cc='ccache gcc -fdiagnostics-color=always' --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module
```

nginx.conf

```yaml
#lua
lua_shared_dict prometheus_metrics 10M;
lua_package_path "/usr/local/openresty/nginx/conf/prometheus.lua;;";
init_worker_by_lua_block {
  prometheus = require("prometheus").init("prometheus_metrics")
  metric_requests = prometheus:counter(
    "nginx_http_requests_total", "Number of HTTP requests", {"host", "status"})
  metric_latency = prometheus:histogram(
    "nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
  metric_connections = prometheus:gauge(
    "nginx_http_connections", "Number of HTTP connections", {"state"})
}
log_by_lua_block {
  metric_requests:inc(1, {ngx.var.server_name, ngx.var.status})
  metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.server_name})
}

server {
  listen 9145;
  server_name localhost;
  allow 192.168.201.0/24;
  deny all;
  location /metrics {
    content_by_lua '
      metric_connections:set(ngx.var.connections_active, {"active"})
      metric_connections:set(ngx.var.connections_reading, {"reading"})
      metric_connections:set(ngx.var.connections_waiting, {"waiting"})
      metric_connections:set(ngx.var.connections_writing, {"writing"})
      prometheus:collect()
    ';
  }
}
```

error.log

```shell
2020/12/29 09:54:44 [error] 13172#13172: *46107 failed to run log_by_lua*: log_by_lua(nginx.conf:37):2: attempt to index global 'metric_requests' (a nil value)
stack traceback:
        log_by_lua(nginx.conf:37):2: in main chunk while logging request, client: 117.136.80.172, server: xx.cn, request: "POST xx.cn/push/v6/msgs HTTP/2.0", upstream: "http://xxx/push/v6/msgs", host: "xx.cn"
2020/12/29 09:54:44 [error] 13173#13173: *46644 failed to run log_by_lua*: log_by_lua(nginx.conf:37):2: attempt to index global 'metric_requests' (a nil value)
stack traceback:
```

**Comment by fsckzy** [comment]
Please help me

**Comment by ponlee** [comment]
I have same question!!!

**Comment by ponlee** [comment]
> > CentOS 7
> > openresty/1.19.3.1
> 
> ```shell
> [root@iZ886g3xpo0Z sbin]# ./nginx -V
> nginx version: openresty/1.19.3.1
> built by gcc 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC) 
> built with OpenSSL 1.1.1h  22 Sep 2020 (running with OpenSSL 1.1.1i  8 Dec 2020)
> TLS SNI support enabled
> configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --with-cc='ccache gcc -fdiagnostics-color=always' --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module
> ```
> 
> nginx.conf
> 
> ```yaml
> #lua
> lua_shared_dict prometheus_metrics 10M;
> lua_package_path "/usr/local/openresty/nginx/conf/prometheus.lua;;";
> init_worker_by_lua_block {
>   prometheus = require("prometheus").init("prometheus_metrics")
>   metric_requests = prometheus:counter(
>     "nginx_http_requests_total", "Number of HTTP requests", {"host", "status"})
>   metric_latency = prometheus:histogram(
>     "nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
>   metric_connections = prometheus:gauge(
>     "nginx_http_connections", "Number of HTTP connections", {"state"})
> }
> log_by_lua_block {
>   metric_requests:inc(1, {ngx.var.server_name, ngx.var.status})
>   metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.server_name})
> }
> 
> server {
>   listen 9145;
>   server_name localhost;
>   allow 192.168.201.0/24;
>   deny all;
>   location /metrics {
>     content_by_lua '
>       metric_connections:set(ngx.var.connections_active, {"active"})
>       metric_connections:set(ngx.var.connections_reading, {"reading"})
>       metric_connections:set(ngx.var.connections_waiting, {"waiting"})
>       metric_connections:set(ngx.var.connections_writing, {"writing"})
>       prometheus:collect()
>     ';
>   }
> }
> ```
> 
> error.log
> 
> ```shell
> 2020/12/29 09:54:44 [error] 13172#13172: *46107 failed to run log_by_lua*: log_by_lua(nginx.conf:37):2: attempt to index global 'metric_requests' (a nil value)
> stack traceback:
>         log_by_lua(nginx.conf:37):2: in main chunk while logging request, client: 117.136.80.172, server: xx.cn, request: "POST xx.cn/push/v6/msgs HTTP/2.0", upstream: "http://xxx/push/v6/msgs", host: "xx.cn"
> 2020/12/29 09:54:44 [error] 13173#13173: *46644 failed to run log_by_lua*: log_by_lua(nginx.conf:37):2: attempt to index global 'metric_requests' (a nil value)
> stack traceback:
> ```

do you use "lua_code_cache off;" ? 
if use, remove it and try again

**Comment by knyar** [comment]
The `attempt to index global 'metric_requests' (a nil value)` message usually means that the library could not be initialized properly. There should be an error message earlier in the log that would help understand why.

Some of the common issues are documented in the [troubleshooting](https://github.com/knyar/nginx-lua-prometheus#troubleshooting) section of the README. If you find another issue not documented there, please feel free to send a PR to help other users.
