### ISSUE TITLE
Problem with remove label_values?

### ISSUE THREAD

**Issue by yangxikun** [knyar/nginx-lua-prometheus#120]
1. del method doesn't remove entry in lookup table, and it will create metric first.
2. When one worker del some label_values, prometheus_keys.lua:KeIndex will sync the change, but lookup table doesn't.(Other worker cannot add again the deleted metrics )

Maybe will cause lookup table size grow up. I suggest refactor lookup table into KeyIndex, make lookup table keep syncing with KeyIndex.

**Comment by knyar** [comment]
Yeah, if you have a high churn of label values in the same long-running nginx instance the lookup table will keep growing. In general, this is not really a use case Prometheus has been designed for, so I would like to avoid too much additional complexity for handling this use case.

Do you see a simple way to fix this, or handle it outside of this library? I am not seeing how KeyIndex will help here, unless you are suggesting to invalidate lookup table in each worker every time `delete_count` is incremented (which I think might be a sensible solution).

@fffonion, I think you were the one who implemented the full metric name lookup table. Any thoughts on getting it synchronized between workers after metric deletion?

**Comment by fffonion** [comment]
Yeah that's a tradeoff from implementing complex sync logic, as I would assume delete is far less frequently called compared to `inc` or `set`. From my understanding if you are retiring metrics very often, it's probably the design of labels is not quite right, and prometheus server will end up with high cardinality.
Back to the question itself, the lookup table is a local "cache". It's volatile and is not a source of truth. So I would lean more to just clean it all, either from lua side or just rely on a SIGHUP to spawn clean worker processes.

**Comment by yangxikun** [comment]
Thanks guys, in my case, delete is far less frequently called. I will call `reset` on each worker timer when metrics with uncertain label values were not need.

**Comment by gwraith** [comment]
> Thanks guys, in my case, delete is far less frequently called. I will call `reset` on each worker timer when metrics with uncertain label values were not need.

when call 'reset' and a metric value is nil, it's key is still in dict
