### ISSUE TITLE
Does not work in nginx/1.18.0 (Ubuntu) and AWS EC2 Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by chamikabm** [knyar/nginx-lua-prometheus#121]
I tried this library in nginx/1.14.0 (Ubuntu) and AWS EC2 Ubuntu 18.04.4 LTS it works perfectly, But again I try this in  nginx/1.18.0 (Ubuntu) and AWS EC2 Ubuntu 20.04.1 LTS, But nginx failed to load. 

**_Here is my nginx config under http :_**
##
# Lua Configs
##
lua_shared_dict prometheus_metrics 10M;
lua_package_path "/etc/nginx/nginx-lua-prometheus/?.lua";
init_worker_by_lua_block {
  prometheus = require("prometheus").init("prometheus_metrics")
  metric_requests = prometheus:counter(
    "nginx_http_requests_total", "Number of HTTP requests", {"host", "status"})
  metric_latency = prometheus:histogram(
    "nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
  metric_connections = prometheus:gauge(
    "nginx_http_connections", "Number of HTTP connections", {"state"})
}
log_by_lua_block {
  metric_requests:inc(1, {ngx.var.server_name, ngx.var.status})
  metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.server_name})
}

**_Here is my server config_**
server {
  listen 9145;
  location /metrics {
    content_by_lua_block {
      metric_connections:set(ngx.var.connections_reading, {"reading"})
      metric_connections:set(ngx.var.connections_waiting, {"waiting"})
      metric_connections:set(ngx.var.connections_writing, {"writing"})
      prometheus:collect()
    }
  }
}

**Comment by knyar** [comment]
This library requires that the lua-nginx-module is actually working. Could you please verify that?

Note that the `libnginx-mod-http-lua` package on Ubuntu 20.04 is broken, I believe (see https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1893753 for more details).

**Comment by chamikabm** [comment]
Thanks @knyar , I'll try the "lua-nginx-module ", Because I was using the "libnginx-mod-http-lua" module.

**Comment by chamikabm** [comment]
![Screenshot 2021-03-16 at 12 06 25 AM](https://user-images.githubusercontent.com/1336559/111184177-ab23f000-85eb-11eb-8757-e57cbac26133.png)
 
 It seems like the package is not available. 
 
My Ubuntu version as follows :
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by chamikabm** [comment]
@knyar Some help would be great in this matter. Thank you very much!

**Comment by knyar** [comment]
One of the ways to have a working Lua module on Ubuntu 20.04 is to rebuild the `libnginx-mod-http-lua` package with this patch that upgrades http-lua module to 0.10.15: https://code.launchpad.net/~knyar/ubuntu/+source/nginx/+git/nginx/+merge/393790

Note that this does not appear to be an issue related related to this library, and I don't personally use Ubuntu. If you get stuck, I would suggest looking for help on one of the Ubuntu-related resources, not here. Good luck!
