### ISSUE TITLE
Grafana example

### ISSUE THREAD

**Issue by lathspell** [knyar/nginx-lua-prometheus#126]
Thank you for this project! As you export to Prometheus, you probably use Grafana to visualize the data.
Could you maybe provide an example, how e.g. a Heatmap or a Graph for the bucket metric could look like and how it's configured?

**Comment by knyar** [comment]
The bucket metric is just a regular prometheus histogram, so there is nothing specific to this library in how to use it in Grafana. I found this document about visualizing histograms in Grafana, perhaps it will be helpful to you: https://grafana.com/blog/2020/06/23/how-to-visualize-prometheus-histograms-in-grafana/
