### ISSUE TITLE
The example of prometheus:histogram in READ.md is wrong.

### ISSUE THREAD

**Issue by 3tgame** [knyar/nginx-lua-prometheus#13]
The example of prometheus:histogram in READ.md is wrong.
The first function should be counter(), the second function should be histogram(), because the parameters count is wrong).

`  metric_latency = prometheus:histogram(
    "nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
  metric_response_sizes = prometheus:counter(
    "nginx_http_response_size_bytes", "Size of HTTP responses", nil,
    {10,100,1000,10000,100000,1000000})
`

**Comment by knyar** [comment]
Actually, both examples are describing histograms. The mistake here is that the second metric is supposed to be a histogram as well. I will get this fixed shortly, thanks.
