### ISSUE TITLE
Support for Gauge and Summary metric types?

### ISSUE THREAD

**Issue by hairyhenderson** [knyar/nginx-lua-prometheus#14]
It looks like this library only supports Histogram and Counter metrics - it'd be useful if this supported all 4 types of prometheus metrics.

It looks like https://github.com/sdurrheimer/nginx-lua-prometheus (a fork of this repo) added support for gauges - maybe that's a place to start? I'd issue a PR, but I'm pretty unfamiliar with Lua.

**Comment by knyar** [comment]
I am open to PRs that add other metric types.

**Comment by knyar** [comment]
Gauges are now supported, and I think histograms are more useful than summaries, but I would not oppose if you wanted to add a summary type either.

**Comment by hairyhenderson** [comment]
Fantastic! Thank you. I agree that histograms are more useful, so this is great for now.
