### ISSUE TITLE
log_by_lua error a nil value

### ISSUE THREAD

**Issue by china-bigcloud** [knyar/nginx-lua-prometheus#142]
failed to run log_by_lua*: log_by_lua(nginx.conf:51):2: attempt to index global 'metric_requests' (a nil value)
![image](https://user-images.githubusercontent.com/25924469/176365624-636650c7-c353-4f51-9fec-6d0dbd52b6a3.png)
![image](https://user-images.githubusercontent.com/25924469/176366089-caec2651-ac25-486b-9e89-33851ba5a7be.png)

**Comment by china-bigcloud** [comment]
![image](https://user-images.githubusercontent.com/25924469/176366362-3f17194d-9ecb-4097-b378-43e21b82cb91.png)

**Comment by MrStack** [comment]
I have the same problem, adn my .conf file is similar.

**Comment by MrStack** [comment]
> 

Whiel I'm using openresty, I solved it by turn lua_code_cache on.

**Comment by knyar** [comment]
> Whiel I'm using openresty, I solved it by turn lua_code_cache on.

That seems to be [documented in README](https://github.com/knyar/nginx-lua-prometheus#keep-lua-code-cache-enabled)

**Comment by MrStack** [comment]
> 

Yes, I've checked the README and find the solution. Thanks
