### ISSUE TITLE
Could you make a new luarocks release?

### ISSUE THREAD

**Issue by kingluo** [knyar/nginx-lua-prometheus#150]
It's been a lot of changes since last release in May (https://luarocks.org/modules/knyar/nginx-lua-prometheus/0.20220527-1).
I depends on some new feature, e.g. eviction.

Could you make a new release and upload to luarocks? Thank you very much!

**Comment by kingluo** [comment]
And I would post a bugfix of memory leak later, related to the lookup table of each metric.
I hope the bugfix would be included in the new release.

**Comment by knyar** [comment]
Sounds good! I will wait for your PR and will be happy to create a new release afterwards. Thank you!

**Comment by knyar** [comment]
Apologies for forgetting about this. I've just created a new release: https://luarocks.org/modules/knyar/nginx-lua-prometheus/0.20221218-1
