### ISSUE TITLE
OS Version Support

### ISSUE THREAD

**Issue by deepakgupta97** [knyar/nginx-lua-prometheus#153]
By when we can expect the support for Debian (22 Version)?

**Comment by knyar** [comment]
This library does not have any OS-specific code, and should be working on any operating system as long as it can run Nginx with the `ngx_lua` module. There were [some issues](https://github.com/knyar/nginx-lua-prometheus#libnginx-mod-http-lua-broken-in-some-debian-and-ubuntu-versions) with `ngx_lua` packages in some versions of Debian and Ubuntu, but there is nothing we can do in this library specifically to address them.
