### ISSUE TITLE
Can add expire time to metrics?

### ISSUE THREAD

**Issue by sugue** [knyar/nginx-lua-prometheus#154]
Now metrics has not expire time, will produce many dirty metrics data.

**Comment by knyar** [comment]
I am not really sure what you mean by "dirty" data. The Prometheus ecosystem convention is for metrics to track everything that has happened with a running process since it was started. Even ability to remove metrics #56 is a bit of an antipattern.

**Comment by sugue** [comment]
Okay.  I just think if i don't need a metrics anymore,  it can be  clean by the library.   Now  i need to write some code to delete useless metrics.
