### ISSUE TITLE
Example for NGINX Stream metrics

### ISSUE THREAD

**Issue by romanqqpr** [knyar/nginx-lua-prometheus#155]
Hello, can you explain how to collect metrics if nginx are using as L4 tcp proxy?

Your example not working 
> server {
>   listen 9145;
>   content_by_lua_block {
>     local sock = assert(ngx.req.socket(true))
>     local data = sock:receive()
>     local location = "GET /metrics"
>     if string.sub(data, 1, string.len(location)) == location then
>       ngx.say("HTTP/1.1 200 OK")
>       ngx.say("Content-Type: text/plain")
>       ngx.say("")
>       ngx.say(table.concat(prometheus:metric_data(), ""))
>     else
>       ngx.say("HTTP/1.1 404 Not Found")
>     end
>   }
> }

This giving me 
`[error] 7#7: *23 lua entry thread aborted: runtime error: content_by_lua(prometheus-metrics.stream:29):14: attempt to index global 'prometheus' (a nil value)
stack traceback:
coroutine 0:
        content_by_lua(prometheus-metrics.stream:29): in main chunk`

**Comment by knyar** [comment]
I am not using the stream module myself, so won't be able to help you with this. Looking at the error message it seems that you might have forgotten to actually import the `nginx-lua-prometheus` library and define your metrics?
