### ISSUE TITLE
Docker nginx:1.24.0-alpine with nginx-mod-http-lua=1.24.0-r2 yields symbol not found

### ISSUE THREAD

**Issue by kennsippell** [knyar/nginx-lua-prometheus#156]
I'm running docker image `nginx:1.24.0-alpine` with alpine package `nginx-mod-http-lua=1.24.0-r2` and looking for help resolving this error:

```
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_lua_module.so" failed (Error relocating /etc/nginx/modules/ngx_http_lua_module.so: pcre_dfa_exec: symbol not found) in /etc/nginx/nginx.conf:1
```

### Dockerfile

Includes:
```
FROM nginx:1.24.0-alpine
RUN apk add --no-cache nginx-mod-http-lua=1.24.0-r2 --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main
```

### nginx.conf

```
load_module modules/ngx_http_lua_module.so;

events {
    worker_connections 10240;
}

http {
    server {
        listen       443 ssl;
...
        location /metrics {
            content_by_lua_block {
                metric_connections:set(ngx.var.connections_reading, {"reading"})
                metric_connections:set(ngx.var.connections_waiting, {"waiting"})
                metric_connections:set(ngx.var.connections_writing, {"writing"})
                prometheus:collect()
            }
        }
    }

    lua_shared_dict prometheus_metrics 10M;
    lua_package_path "/nginx-lua-prometheus-0.20221218/?.lua;;";

    init_worker_by_lua_block {
      prometheus = require("prometheus").init("prometheus_metrics")

      metric_requests = prometheus:counter(
        "nginx_http_requests_total", "Number of HTTP requests", {"host", "status"})
      metric_latency = prometheus:histogram(
        "nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
      metric_connections = prometheus:gauge(
        "nginx_http_connections", "Number of HTTP connections", {"state"})
    }

    log_by_lua_block {
      metric_requests:inc(1, {ngx.var.server_name, ngx.var.status})
      metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.server_name})
    }
}
```

Is this `nginx-mod-http-lua=1.24.0-r2` alpine package meant to be compatible together with the official `nginx:1.24.0-alpine` image? Should I plan to build a non-dynamic version of this library instead of relying on the official package? Or can this be resolved more easily? I'd prefer not to use OpenResty if possible.

Some sources indicate I should also be running `load_module modules/ndk_http_module.so;` first. When I do that, I see:
```
nginx: [emerg] module "/etc/nginx/modules/ndk_http_module.so" is not binary compatible in /etc/nginx/nginx.conf:1
```

Any suggestions appreciated!

**Comment by kennsippell** [comment]
> This is a core component of OpenResty. If you are using this module, then you are essentially using OpenResty :)

https://github.com/openresty/lua-nginx-module

Seems I should maybe just be using OpenResty images...

**Comment by knyar** [comment]
Note that this appears to be an issue with getting [ngx_lua](https://github.com/openresty/lua-nginx-module) module installed rather than something specific to `nginx-lua-prometheus`. I am not a user of Alpine, but I took a look at your PR (https://github.com/medic/cht-core/pull/8208) and tried to suggest next steps. Good luck!

**Comment by kennsippell** [comment]
Wow! Thanks so much for your helpful comments in the PR :D
