### ISSUE TITLE
feature request: Do lua-prometheus support push to Prometheus?

### ISSUE THREAD

**Issue by Adamlixi** [knyar/nginx-lua-prometheus#160]
Isolation network exists in our different environments. We hope to use pushgateway to monitor the nginx.Do lua-prometheus support push to Prometheus? How to do it?

Thanks!

**Comment by knyar** [comment]
No, `nginx-lua-prometheus` does not support pushing metrics to a pushgateway. Prometheus [documentation](https://prometheus.io/docs/practices/pushing/) is pretty clear that pushgateway should be used for monitoring jobs that cannot be scraped, and recommends using [PushProx](https://github.com/prometheus-community/PushProx) if you cannot run Prometheus server in the same network segment as the jobs you are monitoring.
