### ISSUE TITLE
prometheuslib.init is blocked in the init_worker_by_lua_block phase.

### ISSUE THREAD

**Issue by ccechod** [knyar/nginx-lua-prometheus#162]
The Nginx is configured with four worker processes. When I reload the nginx, multiple master processes occur. It is found that the extra master processes are blocked during the prometheuslib.init phase and the CPU usage reaches 99%. The memory usage increases until the memory is fully occupied. Then the VM restarts. In my init worker phase, I flush all the shared memory in the worker 0 process, and then prometheuslib.init. Other worker processes directly prometheuslib.init.

**Comment by knyar** [comment]
Could you please share more details that would allow someone to reproduce this? Ideally a Dockerfile that exhibits this behavior, or at least your nginx configuration as well as repro instructions. Thanks!

**Comment by ccechod** [comment]
init_worker_by_lua_block{
    if ngx.worker.id() == 0 then
            ngx.shared.prometheus_metrics:flush_all()
    end
    prometheus = prometheus.init("prometheus-metrics", metric_prefix)
}
By printing logs, I found that multiple masters were blocked in the prometheus.init function when reloading occurred. The subprocess generated by master fork is not renamed worker process.
The more the number of worker, the easier it is to be triggered.

**Comment by ccechod** [comment]
Is it possible to block in a while true loop in the function KeyIndex:add?

**Comment by ccechod** [comment]
But I review the code and didn't find that there was a possible infinite loop.

**Comment by knyar** [comment]
I don't think this has sufficient information for someone else to be able to easily reproduce and investigate this.

To comment on what you have shared, I find the following lines in the `init_worker_by_lua_block` block surprising:

>if ngx.worker.id() == 0 then
>ngx.shared.prometheus_metrics:flush_all()
>end

Why do you need to remove all metrics on init? Could you please try removing these lines and confirm that you still see high CPU usage on reload?

**Comment by knyar** [comment]
Lacking any response, I am going to close this.

**Comment by WGH-** [comment]
> ` ngx.shared.prometheus_metrics:flush_all()`

This is dangerously wrong.

We did the same mistake. It broke internal variants, and `KeyIndex:add` got stuck in a endless loop.

i.e. `key_count`  was set to 4, but `key_5` was actually occupied.
