### ISSUE TITLE
counter

### ISSUE THREAD

**Issue by elephanter** [knyar/nginx-lua-prometheus#18]
I'm using counter to count requests passed to django backend
'''
nginx.conf:
metric_requests_django = prometheus:counter(
                "nginx_django_requests_total", "Number of HTTP requests", {"host", "status"})

server.conf:
server{
...
location ... {
       uwsgi_pass ...
      log_by_lua '
             local host = ngx.var.host:gsub("^www.", "")
             metric_requests_django:inc(1, {host, ngx.var.status})
        ';
}}
'''

and metrics i've got with this config:

'''
while true; do wget -O - http://nginx_server_ip:9101/metrics -q | grep nginx_django_requests_total | grep lala.my_domain_name | grep 200; sleep 60; done
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 9383
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 9159
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 9185
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 9205
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 9458
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 9245
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 9265
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 9282
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 9301
'''

As you can see counter is not in ascending order.
maybe the problem is because i'm using this host config in nginx:

'''
server_name    ~^(www\.)?(?<sname>[a-z0-9\-]+).my_domain_name;
'''

but that configuration works just fine some time....and last month or two i see that strange problem.
i've updated nginx-lua-prometeus and nginx to latest. that did hot help.

**Comment by knyar** [comment]
This seems like a misconfiguration issue. Looking at the output, I wonder if the counter gets reset to 9101 (which is the port of your metric export virtual host).

Could you please share your full nginx configuration?

**Comment by elephanter** [comment]
no. It isn't reset.
look at the counters today:
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 57769
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 57790
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58070
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58092
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58106
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58144
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 57904
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58183
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58203
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 57966
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58237
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58267
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58278
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58308
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58081
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58349
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58376
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58144
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58418
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58169
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58456
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58465
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58500
nginx_django_requests_total{host="lala.my_domain_name",status="200"} 58508

it seems there is 2 counters mixed. maybe it related with nginx config
'''
worker_processes auto;
'''
sharing full nginx config take time to cut some parts out of it)

**Comment by elephanter** [comment]
by the way. Maybe this is result of calling 'nginx -s reload'. I'm run that command from time to time.

**Comment by knyar** [comment]
Reloading nginx should not have any impact on counters stored in the shared dictionary.

I don't think there is anything I can do to help you with without seeing your config. In any case, both nginx and nginx-lua-prometheus are open source, so if you think something is not working properly, please feel free to investigate and send a patch.

**Comment by elephanter** [comment]
I'm sorry. That was my fault.
I have multiple nginx inside vmware with load balancing enabled. And due to routing configuration my monitoring requests was passed to different nginx hosts.
