### ISSUE TITLE
exclude hosts and remote addresses

### ISSUE THREAD

**Issue by rbosneag** [knyar/nginx-lua-prometheus#20]
More of a question than issue here since I have no experience in Lua.

I am using this library to monitor with Prometheus my nginx server and visualize data with Grafana. 
All well so far except that I have a lot of requests from Prometheus itself and many others from `uptimerobot.com` every few seconds. 

I know I can exclude them from Grafana using labels but I also believe they will affect overall metrics, totals, averages, counters, etc and they also take out disk space, resources, etc. 

I was wondering if there is a way to filter out requests based on a regex applied to nginx variables or a config file with exclusions. An example would be great (I'd even add it to the docs)

Thanks for a great library!

**Comment by knyar** [comment]
I'd suggest making sure that your `log_by_lua` statement only increments metrics for requests you are interested in.

You might be able to filter Uptime Robot by [string matching](http://lua-users.org/wiki/StringLibraryTutorial) over the `User-agent` header (ngx.var.http_user_agent). Prometheus seems like could just use a separate host which has no `log_by_lua` at all.

I hope this helps.

**Comment by rbosneag** [comment]
What I ended up doing is 

```
log_by_lua '  
  if ngx.var.remote_addr ~= "PROMETHEUS_IP" and ngx.var.http_user_agent:find("UptimeRobot") == nil then
        local host = ngx.var.host:gsub("^www.", "")
        metric_requests:inc(1, {host, ngx.var.status})
        metric_latency:observe(ngx.now() - ngx.req.start_time(), {host})
  end
';
``` 
based on your suggestion. 

However, I didn't quite get it what you meant with 

> Prometheus seems like could just use a separate host which has no log_by_lua at all.

since `log_by_lua` is actually set in `nginx.conf` not per location. 

Thanks for the tip, it's working fine anyway (or it seems).

**Comment by knyar** [comment]
Yeah, what I meant is that you could only increment metrics in `log_by_lua` specified for a particular server or location rather than globally.

Anyway, I am glad you got it working.

**Comment by rbosneag** [comment]
I now realize that I could place the `log_by_lua` content per location, not globally as in the README. Anyway, I'm happy with this setup as I can monitor all nginx hosts with the same setup. 

Thanks!
