### ISSUE TITLE
Invalid UTF-8 can be produced

### ISSUE THREAD

**Issue by brian-brazil** [knyar/nginx-lua-prometheus#21]
I got a report of this library producing a label value which included the byte sequence `\xbd\xa6`, which is not valid UTF-8. Please sanitise/correctly encode label values before exposing them to Prometheus, which expects UTF-8.

**Comment by knyar** [comment]
I can see how this might happen if one of the request headers is used as a label value directly (which, sadly, is what the example in README does).

Unicode support in Lua is pretty rudimentary, so I think I will just strip non-ASCII characters from label values.

Could you please point me to user report you received (if it's public, of course)?

**Comment by brian-brazil** [comment]
The report is not public, it was in the host label.

**Comment by brian-brazil** [comment]
Thanks!
