### ISSUE TITLE
Only one metrics : nginx_metric_errors_total?

### ISSUE THREAD

**Issue by dk900912** [knyar/nginx-lua-prometheus#23]
hi, knyar
![image](https://user-images.githubusercontent.com/12511399/29647847-d4fce92e-88bd-11e7-8b63-7d8b9625be5f.png)
![image](https://user-images.githubusercontent.com/12511399/29647860-e538ded8-88bd-11e7-8f8a-2f1df1828a83.png)

Why only one metrics ? thk u

**Comment by knyar** [comment]
What other metrics did you expect? Could you please show the way you are defining and incrementing them in your configuration file?

**Comment by dk900912** [comment]
**If u want to extract some metrics, u must define and increment them in the config file ?**

![image](https://user-images.githubusercontent.com/12511399/29654552-3e2bf814-88e0-11e7-928f-802f5cbe267a.png)
![image](https://user-images.githubusercontent.com/12511399/29654613-76605de2-88e0-11e7-9a07-29bef6b91785.png)
then i find error.log of nginx:
![image](https://user-images.githubusercontent.com/12511399/29654665-a91148aa-88e0-11e7-9b8b-510d4f2491b0.png)

**Comment by knyar** [comment]
Yes, you must define and set metrics in the config file.
What value are you passing for `nginx_http_connections`?

**Comment by dk900912** [comment]
just copy!
![image](https://user-images.githubusercontent.com/12511399/29656011-85eaae2a-88e5-11e7-990b-ec20db5b4643.png)
 I want to add more states, like accepted、handled、active.

**Comment by knyar** [comment]
Maybe your nginx does not export connections_* variables?
Anyway, so far this does not look like a bug in the library, so I will close this issue. If you think there is a bug, please report more details and, preferably, attach a PR.
