### ISSUE TITLE
Consider uploading to OPM

### ISSUE THREAD

**Issue by ChristianCiach** [knyar/nginx-lua-prometheus#26]
If this module is compatible with OpenReste (which I didn't test, but I think it should be), please consider uploading this to OPM: http://opm.openresty.org/

This would make our deployment much easier.

**Comment by knyar** [comment]
Thanks for the suggestion.
I've uploaded the package, and verified that it can be fetched and used by OpenResty.

**Comment by ChristianCiach** [comment]
Thanks a lot!
