### ISSUE TITLE
Unable to install with LuaRocks?

### ISSUE THREAD

**Issue by VanessaHenderson** [knyar/nginx-lua-prometheus#27]
I have a build which installs this in a docker container using the command
`RUN luarocks install nginx-lua-prometheus`
However since you released the new version 2 days ago, this no longer will complete successfully. 
```Installing https://luarocks.org/nginx-lua-prometheus-0.20171117-2.src.rock...
Using https://luarocks.org/nginx-lua-prometheus-0.20171117-2.src.rock... switching to 'build' mode

Error: File not found: nginx-lua-prometheus-0.20171117-2.rockspec
```

Was there something wrong with the release?

**Comment by knyar** [comment]
Thanks for the report! I think I broke luarocks by renaming the rockspec file in 3dcd0fdd8a1183f7ee1a9810797fedc649e8434e, sorry about that.

I've renamed it back, please let me know if this does not fix things.
