### ISSUE TITLE
Collecting metrics from multiple containers

### ISSUE THREAD

**Issue by roshan8** [knyar/nginx-lua-prometheus#28]
Hi,

How do we collect metrics from single box when multiple containers are running on it ?

For example: If 9 containers are running in 2 machines, Those 9 container will be using a random service ports selected by orchestration tool.

In that scenario, How do we collect nginx stats from those 2 boxes (machine-wise/aggregate reports).

Thanks for any help !!

**Comment by knyar** [comment]
This question does not seem specific to the `nginx-lua-prometheus` library.

Typically in Prometheus you would add each process exporting metrics as a separate target, so if you have 9 copies of nginx running, you will have 9 targets. You can then aggregate metrics (usually sum) across various dimensions using Prometheus itself.
