### ISSUE TITLE
how to set for the Specific URL?

### ISSUE THREAD

**Issue by xuanskyer** [knyar/nginx-lua-prometheus#29]
for example:

I wanna monitor the Specific URL: xx.com/my/api，how to init the lua?

**Comment by knyar** [comment]
I believe if you only want metrics incremented for a particular URL, you can either add a `log_by_lua` to the specific nginx `location` section that corresponds to that URL, or just make a decision based on the `ngx.var.uri` lua variable.

**Comment by xuanskyer** [comment]
@knyar tks
ps: nice avatar:)
