### ISSUE TITLE
Histogram values

### ISSUE THREAD

**Issue by LGMAM** [knyar/nginx-lua-prometheus#31]
Hi,
I am integrating this library in our SMS hub and I have a doubt about how histogram works.

I have defined a histogram with the following buckets:

`{0.1,0.25,0.5,0.75,1,2,3,4,5,10,30,60}`

After calling observe the first time (value is 0.275), I get this result in collect:

`sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="00.50"} 1
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="00.75"} 1
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="01.00"} 1
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="02.00"} 1
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="03.00"} 1
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="04.00"} 1
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="05.00"} 1
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="10.00"} 1
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="30.00"} 1
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="60.00"} 1
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="+Inf"} 1
sirocco_latency_seconds_count{endpoint="7",transceiver="80",type="push"} 1
sirocco_latency_seconds_sum{endpoint="7",transceiver="80",type="push"} 0.2759997844696`

There are 2 missing "le" values (0.1 and 0.25). Both buckets are below the passed value (0.1<0.25<0,275). Is this the expected behavior ?

All buckets have a counter of 1. I was expecting this result

`sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="00.10"} 0
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="00.25"} 0
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="00.50"} 1
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="00.75"} 0
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="01.00"} 0
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="02.00"} 0
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="03.00"} 0
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="04.00"} 0
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="05.00"} 0
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="10.00"} 0
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="30.00"} 0
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="60.00"} 0
sirocco_latency_seconds_bucket{endpoint="7",transceiver="80",type="push",le="+Inf"} 0
sirocco_latency_seconds_count{endpoint="7",transceiver="80",type="push"} 1
sirocco_latency_seconds_sum{endpoint="7",transceiver="80",type="push"} 0.2759997844696`

If I send a second value, all buckets will be incremented to 2 as well.

Am I missing something here ?

**Comment by knyar** [comment]
I believe this is the expected behaviour. You might find these links useful:
https://prometheus.io/docs/concepts/metric_types/#histogram
https://www.robustperception.io/why-are-prometheus-histograms-cumulative/

**Comment by LGMAM** [comment]
You are correct. Thanks for the clarification.
