### ISSUE TITLE
Bytes by host or other's flags

### ISSUE THREAD

**Issue by renanberto** [knyar/nginx-lua-prometheus#35]
Hello!
Amazing lib, congratulations.

But I have a question. Can we search inside `metric_response_sizes` for Host, same as` nginx http_requests_total`?

Tks

**Comment by knyar** [comment]
Sure, you'll just need to add another label to the metric definition itself, and provide label values when you set metric values, e.g.
```
metric_response_sizes = prometheus:histogram(
    "nginx_http_response_size_bytes", "Size of HTTP responses", {"host"})
...
metric_response_sizes:observe(tonumber(ngx.var.bytes_sent), {ngx.var.server_name})
```
