### ISSUE TITLE
prometheus.lua:290: bad "zone" argument

### ISSUE THREAD

**Issue by jansonz** [knyar/nginx-lua-prometheus#36]
Running into a issue enabling this and openresty/openresty:1.13.6.1-2-centos Docker baseimages:

gateway_1       | 2018/07/30 20:36:26 [error] 7#7: init_by_lua error: /usr/local/openresty/nginx//lualib/prometheus.lua:290: bad "zone" argument
gateway_1       | stack traceback:
gateway_1       | 	[C]: in function 'set'
gateway_1       | 	/usr/local/openresty/nginx//lualib/prometheus.lua:290: in function 'init'
gateway_1       | 	init_by_lua:3: in main chunk
gateway_1       | nginx: [error] init_by_lua error: /usr/local/openresty/nginx//lualib/prometheus.lua:290: bad "zone" argument
gateway_1       | stack traceback:
gateway_1       | 	[C]: in function 'set'
gateway_1       | 	/usr/local/openresty/nginx//lualib/prometheus.lua:290: in function 'init'
gateway_1       | 	init_by_lua:3: in main chunk

Any ideas?

**Comment by knyar** [comment]
No ideas. I'd suggest taking a look at line 290 of the file, trying to understand where the error message comes from and what the '"zone" argument' is.
