### ISSUE TITLE
Microservices metrics

### ISSUE THREAD

**Issue by chmodrs** [knyar/nginx-lua-prometheus#37]
Hi Knyar,

can i get metrics for specific services?

ex. i have the server_name api.mysite.com;

and locations / 
/api
/v1

where api, v1 are different microservices of same server_name, in /metrics i just got api.mysite.com metrics, and don't api.mysite.com/api 

can you help me in this question?

**Comment by knyar** [comment]
I believe you should be able to add another metric label and populate it with necessary values.
