### ISSUE TITLE
openresty prometheus log_error

### ISSUE THREAD

**Issue by gouki777** [knyar/nginx-lua-prometheus#45]
hi  
my userd prometheus.lua   
my nginx.conf add. 
why  my prometheus  nginx_metric_errors_total error_log?  
I don't know what's wrong  
thanks you   
<pre>
http {  ...... }
lua_shared_dict prometheus_metrics 10M;
lua_package_path "/usr/local/nginx/conf/prometheus.lua";
init_by_lua '
  prometheus = require("prometheus").init("prometheus_metrics")
  metric_requests = prometheus:counter(
    "nginx_http_requests_total", "Number of HTTP requests", {"host", "status"})
  metric_latency = prometheus:histogram(
    "nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
  metric_connections = prometheus:gauge(
    "nginx_http_connections", "Number of HTTP connections", {"state"})
';
log_by_lua '
  metric_requests:inc(1, {ngx.var.server_name, ngx.var.status})
  metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.server_name})
';
</pre>
<pre>
# /usr/local/nginx/sbin/nginx -V
nginx version: openresty/1.13.6.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty-1.13.6.2/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.13 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.5 --with-ld-opt=-Wl,-rpath,/usr/local/openresty-1.13.6.2/luajit/lib --user=nobody --group=nobody --with-stream --with-stream_ssl_module --with-http_ssl_module
</pre>

----log_error----
<pre>
[root@localhost conf]# curl -i 127.0.0.1/metrics
HTTP/1.1 200 OK
Server: ORifeng/1.13.6.2
Date: Sat, 29 Dec 2018 10:21:50 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive

# HELP nginx_http_request_duration_seconds HTTP request latency
# TYPE nginx_http_request_duration_seconds histogram
nginx_http_request_duration_seconds_bucket{host="localhost",le="00.005"} 22
......
# HELP nginx_http_requests_total Number of HTTP requests
# TYPE nginx_http_requests_total counter
nginx_http_requests_total{host="localhost",status="200"} 15
# HELP nginx_metric_errors_total Number of nginx-lua-prometheus errors
# TYPE nginx_metric_errors_total counter
nginx_metric_errors_total 15                            <<<<<--------------

# tail -f /usr/local/nginx/logs/error.log 
2018/12/29 18:15:37 [error] 115210#0: *19 [lua] prometheus.lua:295: log_error(): No value passed for nginx_http_connections, client: 127.0.0.1, server: localhost, request: "GET /metrics HTTP/1.1", host: "127.0.0.1"
</pre>

**Comment by knyar** [comment]
It seems like you are passing a `nil` value to `metric_connections:set()`.

It might be caused by the fact that you don't have the [ngx_http_stub_status_module](http://nginx.org/en/docs/http/ngx_http_stub_status_module.html) module enabled and there is no `ngx.var.connections_reading` variable.

**Comment by gouki777** [comment]
thank you.
My add ngx_http_stub_status_module is OK.
