### ISSUE TITLE
Release version 0.20181120 on GitHub

### ISSUE THREAD

**Issue by pracucci** [knyar/nginx-lua-prometheus#46]
May you create a tagged release for `0.20181120` on GitHub, so that we can download the sources by version tag instead of commit hash, please?

**Comment by knyar** [comment]
Sorry, I missed the notification about this issue for some reason.

Just created [the tag](https://github.com/knyar/nginx-lua-prometheus/tree/0.20181120) and also adjusted README to make sure I continue doing so in the future.

Thanks for reporting this!

**Comment by pracucci** [comment]
Thanks!
