### ISSUE TITLE
Getting Error  unknown directive "lua_package_path" in /etc/nginx/nginx.conf

### ISSUE THREAD

**Issue by anishvarghese** [knyar/nginx-lua-prometheus#48]
Getting Error  unknown directive "lua_package_path" in /etc/nginx/nginx.conf

**Comment by knyar** [comment]
The most likely reason is that you don't have the `lua` module enabled.

**Comment by anishvarghese** [comment]
I am using nginx 1.14 with Ubuntu 18. I sued the command suggested in your Readme and confirmed the modules are there in the module directory but it still showing this issue
```
root@prod:/usr/share/nginx/modules# ls -al
total 752
drwxr-xr-x 2 root root   4096 Feb  8 08:39 .
drwxr-xr-x 3 root root   4096 Dec  5 10:51 ..
-rw-r--r-- 1 root root  14440 Nov  6 18:54 ndk_http_module.so
-rw-r--r-- 1 root root  20232 Nov  6 18:54 ngx_http_geoip_module.so
-rw-r--r-- 1 root root  23472 Nov  6 18:54 ngx_http_image_filter_module.so
-rw-r--r-- 1 root root 413520 Nov  6 18:54 ngx_http_lua_module.so
-rw-r--r-- 1 root root  19304 Nov  6 18:54 ngx_http_xslt_filter_module.so
-rw-r--r-- 1 root root  99720 Nov  6 18:54 ngx_mail_module.so
-rw-r--r-- 1 root root 163272 Nov  6 18:54 ngx_stream_module.so
```

**Comment by anishvarghese** [comment]
enabled the module and fixed the issue now getting this
root@prod:/usr/share/nginx/modules# nginx -t
nginx: [error] [lua] prometheus.lua:271: init(): Dictionary 'prometheus_metrics' does not seem to exist. Please define the dictionary using `lua_shared_dict`.
nginx: [error] [lua] prometheus.lua:316: counter(): Prometheus module has not been initialized
nginx: [error] [lua] prometheus.lua:384: histogram(): Prometheus module has not been initialized
nginx: [error] [lua] prometheus.lua:349: gauge(): Prometheus module has not been initialized
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by sara4dev** [comment]
I also faced the same error. I had to include these two lines at the top of the nginx.conf, and that solved it.

```
load_module modules/ndk_http_module.so;
load_module modules/ngx_http_lua_module.so;
```

**Comment by SeanQuinn781** [comment]
> I also faced the same error. I had to include these two lines at the top of the nginx.conf, and that solved it.
> 
> ```
> load_module modules/ndk_http_module.so;
> load_module modules/ngx_http_lua_module.so;
> ```

Thanks worked for me

**Comment by smac89** [comment]
Note: You should specify the full path to the module if they are not located in the `$NGINX_PREFIX` (ex. `/etc/nginx`)
