### ISSUE TITLE
Issues with starting Lua directory

### ISSUE THREAD

**Issue by anishvarghese** [knyar/nginx-lua-prometheus#49]
nginx: [error] [lua] prometheus.lua:271: init(): Dictionary 'prometheus_metrics' does not seem to exist. Please define the dictionary using `lua_shared_dict`.
nginx: [error] [lua] prometheus.lua:316: counter(): Prometheus module has not been initialized
nginx: [error] [lua] prometheus.lua:384: histogram(): Prometheus module has not been initialized
nginx: [error] [lua] prometheus.lua:349: gauge(): Prometheus module has not been initialized

**Comment by anishvarghese** [comment]
Pleae find my configuration 
## NGinx Prometheus Configuration
lua_shared_dict prometheus_metrics 10M;
lua_package_path "/opt/exporters/nginx-lua-prometheus/?.lua";
init_by_lua '
  prometheus = require("prometheus").init("prometheus_metrics")
  metric_requests = prometheus:counter(
    "nginx_http_requests_total", "Number of HTTP requests", {"host", "status"})
  metric_latency = prometheus:histogram(
    "nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
  metric_connections = prometheus:gauge(
    "nginx_http_connections", "Number of HTTP connections", {"state"})
';
log_by_lua '
  metric_requests:inc(1, {ngx.var.server_name, ngx.var.status})
  metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.server_name})
';

**Comment by knyar** [comment]
Configuration looks reasonable. This seems like a problem specific to your environment rather than an issue with `nginx-lua-prometheus`, so I don't think I can provide any assistance, sorry.
