### ISSUE TITLE
Sum / Count returns NaN

### ISSUE THREAD

**Issue by zevarito** [knyar/nginx-lua-prometheus#5]
I was following this article: https://prometheus.io/docs/practices/histograms, checking metrics suggested there vs the one I've already added.

For the simplest one that should be:

```
 rate(nginx_http_request_duration_seconds_sum[5m])
/
 rate(nginx_http_request_duration_seconds_count[5m])
```

I am getting NaN values in Prometheus console, do you know something about that behavior?

**Comment by balaakurakula** [comment]
If a request has never happened then the rate_duration_seconds_couny will be 0 which will give you the NaN..
