### ISSUE TITLE
Stream Dictionary?

### ISSUE THREAD

**Issue by InTheCloudDan** [knyar/nginx-lua-prometheus#50]
I'm having trouble getting metrics working with the stream module based on the readme because `lua_shared_dict` will not work in that block. Is there a different way to store the metrics for them to be readable?

**Comment by knyar** [comment]
I've not used the stream module myself, but I believe you will need to define the shared dictionary and metrics as part of the `stream {}` section of configuration (rather than the `http {}` section).

What README shows is how to expose metrics to Prometheus via a TCP endpoint.

**Comment by midorinet** [comment]
do you find any solution for this?
