### ISSUE TITLE
Nginx metrics based on path and method

### ISSUE THREAD

**Issue by rjshrjndrn** [knyar/nginx-lua-prometheus#51]
Hi,
Thank you for this awesome plugin. Helped me to get rid of logspout, logstash and statsd.
But some small clarifications.
1. is it possible to get custom metrics( like per path or incoming ip/server)
2. Is it possible to gather metrics with methods(GET, POST, OPTIONS)

and one doubt,
while looking at `nginx_http_requests_total` I saw

`nginx_http_requests_total{host="xxx.yyy.com",instance="10.0.0.156:9145",job="nginx_prom",status="200"}    58408 `
and 
`nginx_http_requests_total{instance="10.0.0.156:9145",job="nginx_prom",status="200"}    138`

one with instance and one without. What's this? 

I am running nginx in docker swarm, with 6 replicas, and prometheus `dns_sd` to discover nodes.

--

Thank you.

**Comment by rjshrjndrn** [comment]
I found the solution. Thank you for the awesome plugin once again. Preparing documentation, How I did it for nginx running in a swarm. If you're interested I can raise PR. It'll be an honor.

**Comment by rjshrjndrn** [comment]
Sorry,
I got the solution for 1 and 2. But the doubt is still not clarified. What's that 2 metrics with same name and different tags?

**Comment by knyar** [comment]
A time series in Prometheus is identified by a metric name and a combination of labels, so it's completely normal to have several metrics with the same name and different labels.

In your example it seems like you either added or removed the `host` label at some point.
