### ISSUE TITLE
Plugins will double CPU utilization  please optimize?

### ISSUE THREAD

**Issue by taotao2014** [knyar/nginx-lua-prometheus#53]
Plugins will double CPU utilization  please optimize?

**Comment by taotao2014** [comment]
@knyar
@cherti
@stas-dubrovskyi
@sergakaibis
@calixwu

**Comment by knyar** [comment]
I don't believe this is actionable the way it's currently phrased.

If you could provide data showing where specifically excessive CPU utilization occurs and suggestions on how CPU usage could be decreased, I will be happy to review your design and code, and collaborate on improvements.

**Comment by taotao2014** [comment]
performance decline:
1. prometheus.lua : function Prometheus:histogram_observe,line 479
2. handler.lua : local ok, err = ngx.timer.at(0, log, conf, message),line 29 (Context switching)

@knyar

**Comment by taotao2014** [comment]
@knyar
