### ISSUE TITLE
Invitation to DevOpsConf Russia on September 30th and October 1st 2019

### ISSUE THREAD

**Issue by smith3v** [knyar/nginx-lua-prometheus#57]
Hi Anton.

My name is Slava, I’m an engineer at Ecwid. I’m representing DevOpsConf Russia program committee. We are carrying out the most practical conference for those involved in processes of test automation, creating an infrastructure platform, CTO and anyone who wants to know how DevOps works for others. The community has grown a lot and in addition to separate tracks at the Russian Internet technologies festival and HighLoad++ conference, we will also hold an independent two-day conference this autumn.

I found your name [among authors of Google’s SRE book](https://landing.google.com/sre/workbook/chapters/monitoring/). So I decided you have something to share with the Russian engineering community. On behalf of organizing committee I would like to make a special invitation to you as a speaker :) If you’ll come up with several topics you might want to talk about, we can discuss them all in order to find the most efficient way to present your work and get maximum response from our audience. Also we can choose several, if you decide to come to us more than once.

You can apply [here](https://conf.ontico.ru/lectures/propose?conference=dc2019-moscow).

If any questions, please don’t hesitate to ask me in telegram @smith3v

Thank you and have a nice day!

P.S. Sorry, I didn't find better way to contact you.

**Comment by knyar** [comment]
Hi Slava!

Thank you for the invitation, I do appreciate it.
Unfortunately I will not be able to join DevOpsConf Russia.

Cheers, Anton
