### ISSUE TITLE
How to persist data？

### ISSUE THREAD

**Issue by SenXuDC** [knyar/nginx-lua-prometheus#58]
I use docker to run nginx  with promethues.lua. But the container restart or recreate, old data is loss, how can I persistent data? thanks

**Comment by knyar** [comment]
You will need to configure a [Prometheus server](https://prometheus.io/) to collect and persist metric values.

**Comment by SenXuDC** [comment]
When I restart nginx, the metric data provided by port 9145 starts at 0 again.
