### ISSUE TITLE
/metrics aren't displayed, downloaded instead

### ISSUE THREAD

**Issue by simonszu** [knyar/nginx-lua-prometheus#6]
Hi,

not really an issue, but a question instead. It seems that any browser does not recognize the /metrics path as a text file it can display, but as a binary (or other file type it can't handle), so it downloads the file instead. When viewing the downloaded file with a text editor it looks fine. 
So i am questioning myself if i haven't set up this plugin correctly, and prometheus itself will fail interpreting the /metrics as well, or if everything is fine?
If this is the expected behaviour, maybe you could specify some kind of output MIME-type so that the average browser can handle the output?
This would prevent other noobs like me who have very little experience with the collaboration of nginx and lua from searching for errors when there are none.

**Comment by knyar** [comment]
I think the latest commit should fix this.

**Comment by simonszu** [comment]
It does. Thank you very much.
