### ISSUE TITLE
Grafana dashboard template

### ISSUE THREAD

**Issue by saviour123** [knyar/nginx-lua-prometheus#66]
- Is there a way to provision a grafana dashboard JSON with the project so anyone can easily pull from grafana plugins.

**Comment by knyar** [comment]
Thanks for the suggestion! Each deployment of this plugin is expected to have a different set of metrics defined (specific for a given system), so I don't think that providing a universal Grafana dashboard is feasible, unfortunately.

**Comment by Self-Perfection** [comment]
But metrics defined in quick start guide are quite good as a foothold. I have found https://grafana.com/grafana/dashboards/10223 that works really good with metrics from quick start guide. I might tune this in future but this will unlikely to happen soon.

Thus I suppose providing link to https://grafana.com/grafana/dashboards/10223 in quick start guide as an example is helpful.
