### ISSUE TITLE
No value passed for nginx_http_connections

### ISSUE THREAD

**Issue by ghost** [knyar/nginx-lua-prometheus#67]
# Expose prometheus's metrics scrape port
server {
    listen 9145;
    allow all;
    access_log off;
    location /metrics {
      content_by_lua '
        metric_connections:set(ngx.var.connections_reading, {"reading"})
        metric_connections:set(ngx.var.connections_waiting, {"waiting"})
        metric_connections:set(ngx.var.connections_writing, {"writing"})
        prometheus:collect()
      ';
    }
}
--------------
why can not get the metrics "nginx_http_connections"   ??
 ------------
error:

2019/11/07 18:25:01 [error] 123564#0: *761153 [lua] prometheus.lua:365: log_error(): No value passed for nginx_http_connections, client: 172.18.0.1, server: , request: "GET /metrics HTTP/1.1", host: "172.18.0.203:9145"
2019/11/07 18:25:01 [error] 123564#0: *761153 [lua] prometheus.lua:365: log_error(): No value passed for nginx_http_connections, client: 172.18.0.1, server: , request: "GET /metrics HTTP/1.1", host: "172.18.0.203:9145"
2019/11/07 18:25:01 [error] 123564#0: *761153 [lua] prometheus.lua:365: log_error(): No value passed for nginx_http_connections, client: 172.18.0.1, server: , request: "GET /metrics HTTP/1.1", host: "172.18.0.203:9145"

**Comment by knyar** [comment]
It seems that you don't have a `connections_reading` variable available in your nginx. Looking at the documentation, I believe this variable is provided by the [ngx_http_stub_status_module](http://nginx.org/en/docs/http/ngx_http_stub_status_module.html). Could you please check that you have that module enabled?
