### ISSUE TITLE
Getting constant "Lua VM crashed" error

### ISSUE THREAD

**Issue by dutsky** [knyar/nginx-lua-prometheus#68]
Hello! I have nginx 1.17.3, libluajit 2.1.0  nginx-module-lua and trying your to use your module with default settings

but every time prometheus connecting to /metrics I have this error in my nginx error.log:
```
nginx: lua atpanic: Lua VM crashed, reason: attempt to call a thread value
nginx: lua atpanic: Lua VM crashed, reason: attempt to call a thread value
nginx: lua atpanic: Lua VM crashed, reason: attempt to call a thread value
nginx: lua atpanic: Lua VM crashed, reason: attempt to call a thread value
nginx: lua atpanic: Lua VM crashed, reason: attempt to call a thread value
nginx: lua atpanic: Lua VM crashed, reason: attempt to call a thread value
nginx: lua atpanic: Lua VM crashed, reason: attempt to call a thread value
```

prometheus can't get values from /metrics

Maybe I do something wrong? Can you give any suggestions please?

**Comment by knyar** [comment]
This is not an issue I've encountered myself, and the error message does not make it particularly obvious what's going on.

Do you think you could share a `Dockerfile` I could use to reproduce this?

**Comment by dutsky** [comment]
Sorry for disturbing you. It seems it was broken ngx-module-lua or something like this.
