### ISSUE TITLE
nginx_http_requests_total   cannot add  labels  uri

### ISSUE THREAD

**Issue by arrow2012** [knyar/nginx-lua-prometheus#70]
nginx_http_requests_total only have host and status metrics

nginx_http_requests_total{host="",status="200"} 2

I think it should have a labels uri 
nginx_http_requests_total{host="",uri="/api/v1/users",status="200"} 2
nginx_http_requests_total{host="",uri="/api/v1/hosts",status="200"} 2

I add it to init_by_lua_block{}

init_by_lua_block {
  require "resty.core"
  prometheus = require("prometheus").init("prometheus_metrics")
  metric_bytes = prometheus:counter(
    "nginx_http_request_size_bytes", "Total size of incoming requests")
  metric_requests = prometheus:counter(
    "nginx_http_requests_total", "Number of HTTP requests", {"host","url", "status"})
  metric_latency = prometheus:histogram(
    "nginx_http_request_duration_seconds", "HTTP request latency", {"host","url"})
  metric_connections = prometheus:gauge(
    "nginx_http_connections", "Number of HTTP connections", {"state"})
  metric_response_sizes = prometheus:histogram(
    "nginx_http_response_size_bytes", "Size of HTTP responses", nil,
    {10,100,1000,10000,100000,1000000})
}
but it is not work

**Comment by knyar** [comment]
You also need to adjust the `log_by_lua` block to pass another label value.

Please note that adding URL as a metric label might significantly increase the number of metrics tracked by the library which has some [performance implications](https://github.com/knyar/nginx-lua-prometheus#large-number-of-metrics).
