### ISSUE TITLE
lua-resty-counter is impossible to pin

### ISSUE THREAD

**Issue by dav-is** [knyar/nginx-lua-prometheus#80]
https://github.com/knyar/nginx-lua-prometheus/blob/master/prometheus_resty_counter.update.sh references the master version of the lib. They could ship a new breaking change that breaks this lib.

**Comment by knyar** [comment]
Yeah, they could, but in that case hopefully the tests will start failing and the broken version of the counter library will not be committed.

Perhaps it is not very clear that the purpose of that script is to make it easier for me to update the "vendored" library in this repo, and users should not need to run it. I will try to make it more clear.
