### ISSUE TITLE
How to get error metric of website

### ISSUE THREAD

**Issue by messi655** [knyar/nginx-lua-prometheus#9]
Hi @knyar ,

Thanks for your script, it's very helpful for me.
But If I want to get the metrics error of my website (ex: www.example.com) how can I do that?
Please give me some suggest.

thanks,
Tin

**Comment by knyar** [comment]
If you follow the "Quick start guide" section in README.md, you should get a `nginx_http_requests_total` metric with HTTP status code as a separate field. You can then use Prometheus to see the number of requests that resulted in a response with code 500.

For example, to see the rate of errors per host, you could use the following expression: `sum(rate(nginx_http_requests_total{status=~"5.."}[2m])) by (host)`

**Comment by messi655** [comment]
thanks @knyar 

I don't understand the results from metrics:

nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.005"} 62
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.010"} 63
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.020"} 757
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.030"} 1111
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.050"} 1225
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.075"} 1269
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.100"} 1315
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.200"} 1489
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.300"} 1679
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.400"} 1873
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.500"} 2073
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.750"} 8649
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="01.000"} 8692
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="01.500"} 8695
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="02.000"} 8695
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="03.000"} 8695
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="04.000"} 8695
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="05.000"} 8695
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="10.000"} 9262
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="+Inf"} 9548
nginx_http_request_duration_seconds_count{host="prometheus.tin.lzd"} 9548
nginx_http_request_duration_seconds_sum{host="prometheus.tin.lzd"} 12351.464051723 

could you help me explain this, example
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.400"} 1873
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="00.500"} 2073
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="05.000"} 8695
nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="10.000"} 9262

what's it mean?

nginx_http_request_duration_seconds_bucket{host="prometheus.tin.lzd",le="+Inf"} 9548

what's it mean?

nginx_http_request_duration_seconds_count{host="prometheus.tin.lzd"} 9548
nginx_http_request_duration_seconds_sum{host="prometheus.tin.lzd"} 12351.464051723 

what's it mean?

thanks

**Comment by messi655** [comment]
one more: buckets is an array of numbers defining bucket boundaries. Optional, defaults to 20 latency buckets covering a range from 5ms to 10s (in seconds).

=> what is bucket boundaries?

thanks

**Comment by knyar** [comment]
Originally you asked about error count metric, but your later comments refer to the latency metrics.
Prometheus documentation describing histograms might be helpful: https://prometheus.io/docs/concepts/metric_types/#histogram

**Comment by messi655** [comment]
thanks for your quick response.

**Comment by messi655** [comment]
@knyar  can you explain "nginx_metric_errors_total " what's this mean?

Thanks,

**Comment by knyar** [comment]
@messi655 I think it's described in the README: https://github.com/knyar/nginx-lua-prometheus#built-in-metrics
